name: code_check

on:
  push:
    branches: [ main ]
  pull_request:
    branches: [ main ]


jobs:
  build:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v2
      - name: Install Python
        run: sudo apt install python3.10
      - name: Install deps
        run: pip install -r requirements.txt
      - name: Run flake8
        run: flake8 .
      - name: Pytest
        run: pytest
