name: code_check

on:
  push:
    branches: [ main ]
  pull_request:
    branches: [ main ]


jobs:
  build:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v2
      - name: Install Python
        run: sudo apt install python3.10
      - name: Install deps
        run: pip install -r requirements.txt
      - name: Run flake8
        run: flake8 .
      - name: Pytest
        run: pytest
      - name: Install Docker
        run: |
          curl -fsSL https://get.docker.com -o get-docker.sh
          DRY_RUN=1 sudo sh ./get-docker.sh
      - name: build Docker
        run: docker build -t myimage .
      - name: run Docker and healthcheck
        run: docker run -d --name mycontainer -p 80:80 myimage
        run: curl http://127.0.0.1/health_check